### PR TITLE
Adding level & category to LoggingAction

### PR DESCRIPTION
**Pull request by aochsner**

### CODE REVIEW

**Comment by gmarz** [comment]
Thanks again @aochsner, I left one small comment, otherwise this looks good.

**Comment by aochsner** [comment]
Good suggestion.  Updated!

**Comment by gmarz** [comment]
Awesome!  Thanks @aochsner

**Comment by aochsner** [comment]
Ack!  You're right.  That's what I get for making hasty changes

**Comment by aochsner** [comment]
Sorry, left out https://github.com/aochsner/elasticsearch-watcher-net/commit/f2112d412a5f2e7da4721fcb036d0d468954c929 as well!

**Pull request merged**
